<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => array (
      'regex_matches' => array ('6\\.5\\.(.*?)', '6\\.6\\.(.*?)', '6\\.6\\.(.*?)\\.(.*?)', '6\\.7\\.(.*?)', '6\\.7\\    .(.*?)\\.(.*?)'),
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      'PRO','CORP','ENT','ULT'
    ),
  ),
  'readme' => '',
  'key' => 'up',
  'author' => 'dbergeron',
  'description' => 'User Preferences Mass Update',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'UserPreferences',
  'published_date' => '2013-08-23 14:16:32',
  'type' => 'module',
  'version' => 1377267392,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'UserPreferences',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'up_UserPreferences',
      'class' => 'up_UserPreferences',
      'path' => 'modules/up_UserPreferences/up_UserPreferences.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/up_userpreferences_users_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/up_userpreferences_users_1_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/up_userpreferences_usersMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/up_userpreferences_users_1MetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/up_UserPreferences',
      'to' => 'modules/up_UserPreferences',
    ),
    1 => array(
        'from' => '<basepath>/Files/custom/Extension/application/Ext/Utils/userpreferences_utils.php',
        'to' => 'custom/Extension/application/Ext/Utils/userpreferences_utils.php',
        ),
    2 => array(
        'from' => '<basepath>/Files/custom/Extension/modules/Administration/Ext/Administration/UserPreferences.php',
        'to' => 'custom/Extension/modules/Administration/Ext/Administration/UserPreferences.php',
        ),
    3 => array(
        'from' => '<basepath>/Files/custom/Extension/modules/up_UserPreferences/Ext/Language/en_us.UserPreferences.php',
        'to' => 'custom/Extension/modules/up_UserPreferences/Ext/Language/en_us.UserPreferences.php',
        ),
    4 => array(
        'from' => '<basepath>/Files/custom/Extension/modules/up_UserPreferences/Ext/Layoutdefs/up_userpreferences_users_1_up_UserPreferences.php',
        'to' => 'custom/Extension/modules/up_UserPreferences/Ext/Layoutdefs/up_userpreferences_users_1_up_UserPreferences.php',
        ),
    5 => array(
        'from' => '<basepath>/Files/custom/Extension/modules/up_UserPreferences/Ext/Layoutdefs/up_userpreferences_users_up_UserPreferences.php',
        'to' => 'custom/Extension/modules/up_UserPreferences/Ext/Layoutdefs/up_userpreferences_users_up_UserPreferences.php',
        ),
    6 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/Classes/Layouts.php',
        'to' => 'modules/up_UserPreferences/Classes/Layouts.php',
        ),
    7 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/Dashlets/up_UserPreferencesDashlet/up_UserPreferencesDashlet.meta.php',
        'to' => 'modules/up_UserPreferences/Dashlets/up_UserPreferencesDashlet/up_UserPreferencesDashlet.meta.php',
        ),
    8 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/Dashlets/up_UserPreferencesDashlet/up_UserPreferencesDashlet.php',
        'to' => 'modules/up_UserPreferences/Dashlets/up_UserPreferencesDashlet/up_UserPreferencesDashlet.php',
        ),
    9 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/css/dragdrop.css',
        'to' => 'modules/up_UserPreferences/css/dragdrop.css',
        ),
    10 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/js/dragdrop.js',
        'to' => 'modules/up_UserPreferences/js/dragdrop.js',
        ),
    11 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/vardefs.php',
        'to' => 'modules/up_UserPreferences/vardefs.php',
        ),
    12 => array(
        'from' => '<basepath>/Files/modules/up_UserPreferences/up_UserPreferences.php',
        'to' => 'modules/up_UserPreferences/up_UserPreferences.php',
        ),
    ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ko_KR',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lv_LV',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nb_NO',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nl_NL',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pl_PL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_PT',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ro_RO',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sv_SE',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'tr_TR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'zh_CN',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_BR',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ca_ES',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_UK',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sr_RS',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sk_SK',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sq_AL',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'bg_BG',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'cs_CZ',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'da_DK',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'de_DE',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'el_EL',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'es_ES',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'fr_FR',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'he_IL',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'hu_HU',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'it_it',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'lt_LT',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ja_JP',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ko_KR',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'lv_LV',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'nb_NO',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'nl_NL',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pl_PL',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pt_PT',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ro_RO',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ru_RU',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sv_SE',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'tr_TR',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'zh_CN',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pt_BR',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ca_ES',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'en_UK',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sr_RS',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sk_SK',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sq_AL',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'bg_BG',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'cs_CZ',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'da_DK',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'de_DE',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'el_EL',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'es_ES',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'fr_FR',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'he_IL',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'hu_HU',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'it_it',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lt_LT',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ja_JP',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ko_KR',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lv_LV',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nb_NO',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nl_NL',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pl_PL',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_PT',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ro_RO',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sv_SE',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'tr_TR',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'zh_CN',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_BR',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ca_ES',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_UK',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sr_RS',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sk_SK',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sq_AL',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'en_us',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'bg_BG',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'cs_CZ',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'da_DK',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'de_DE',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'el_EL',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'es_ES',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'fr_FR',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'he_IL',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'hu_HU',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'it_it',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'lt_LT',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ja_JP',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ko_KR',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'lv_LV',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'nb_NO',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'nl_NL',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pl_PL',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pt_PT',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ro_RO',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ru_RU',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sv_SE',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'tr_TR',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'zh_CN',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'pt_BR',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'ca_ES',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'en_UK',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sr_RS',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sk_SK',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
      'language' => 'sq_AL',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/up_userpreferences_users_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/up_userpreferences_users_Users.php',
      'to_module' => 'Users',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/up_userpreferences_users_1_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/up_userpreferences_users_1_Users.php',
      'to_module' => 'Users',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'up_userpreferences_users_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'up_userpreferences_users_1_name',
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/up_userpreferences_users_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/up_userpreferences_users_1_up_UserPreferences.php',
      'to_module' => 'up_UserPreferences',
    ),
  ),
);
