<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$dictionary['up_UserPreferences'] = array(
	'table'=>'up_userpreferences',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'date_format' => 
  array (
    'required' => false,
    'name' => 'date_format',
    'vname' => 'LBL_DATE_FORMAT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'date_format_list',
    'studio' => 'visible',
    'dependency' => 'equal($date_format_enable,true)',
    'function' => 'up_getDateFormats',
  ),
  'date_format_enable' => 
  array (
    'required' => false,
    'name' => 'date_format_enable',
    'vname' => 'LBL_DATE_FORMAT_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'time_format' => 
  array (
    'required' => false,
    'name' => 'time_format',
    'vname' => 'LBL_TIME_FORMAT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'time_format_list',
    'studio' => 'visible',
    'dependency' => 'equal($time_format_enable,true)',
    'function' => 'up_getTimeFormats',
  ),
  'time_format_enable' => 
  array (
    'required' => false,
    'name' => 'time_format_enable',
    'vname' => 'LBL_TIME_FORMAT_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'timezone' => 
  array (
    'required' => false,
    'name' => 'timezone',
    'vname' => 'LBL_TIMEZONE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'Africa/Algiers',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'timezone_dom',
    'studio' => 'visible',
    'dependency' => 'equal($timezone_enable,true)',
  ),
  'timezone_enable' => 
  array (
    'required' => false,
    'name' => 'timezone_enable',
    'vname' => 'LBL_TIMEZONE_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'first_day_week' => 
  array (
    'required' => false,
    'name' => 'first_day_week',
    'vname' => 'LBL_FIRST_DAY_WEEK',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'dom_cal_day_long',
    'studio' => 'visible',
    'dependency' => 'equal($first_day_of_the_week_enable,true)',
    'default' => '0',
  ),
  'first_day_of_the_week_enable' => 
  array (
    'required' => false,
    'name' => 'first_day_of_the_week_enable',
    'vname' => 'LBL_FIRST_DAY_OF_THE_WEEK_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'currency' => 
  array (
    'required' => false,
    'name' => 'currency',
    'vname' => 'LBL_CURRENCY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($currency_enable,true)',
    'function' => 'up_getCurrencies',
  ),
  'currency_significant_digit_ena' => 
  array (
    'required' => false,
    'name' => 'currency_significant_digit_ena',
    'vname' => 'LBL_CURRENCY_SIGNIFICANT_DIGIT_ENA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'decimal_symbol' => 
  array (
    'required' => false,
    'name' => 'decimal_symbol',
    'vname' => 'LBL_DECIMAL_SYMBOL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($decimal_symbol_enable,true)',
  ),
  'decimal_symbol_enable' => 
  array (
    'required' => false,
    'name' => 'decimal_symbol_enable',
    'vname' => 'LBL_DECIMAL_SYMBOL_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'thousands_separator' => 
  array (
    'required' => false,
    'name' => 'thousands_separator',
    'vname' => 'LBL_THOUSANDS_SEPARATOR',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($thousands_separator_enable,true)',
  ),
  'thousands_separator_enable' => 
  array (
    'required' => false,
    'name' => 'thousands_separator_enable',
    'vname' => 'LBL_THOUSANDS_SEPARATOR_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'email_client' => 
  array (
    'required' => false,
    'name' => 'email_client',
    'vname' => 'LBL_EMAIL_CLIENT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'sugar',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'dom_email_link_type',
    'studio' => 'visible',
    'dependency' => 'equal($email_client_enable,true)',
  ),
  'themes' => 
  array (
    'required' => false,
    'name' => 'themes',
    'vname' => 'LBL_THEMES',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'themes_list',
    'studio' => 'visible',
    'dependency' => 'equal($themes_enable,true)',
    'function' => 'up_getThemes',
  ),
  'email_client_enable' => 
  array (
    'required' => false,
    'name' => 'email_client_enable',
    'vname' => 'LBL_EMAIL_CLIENT_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'themes_enable' => 
  array (
    'required' => false,
    'name' => 'themes_enable',
    'vname' => 'LBL_THEMES_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'layout_options' => 
  array (
    'required' => false,
    'name' => 'layout_options',
    'vname' => 'LBL_LAYOUT_OPTIONS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($layout_options_enable,true)',
    'function' => 'up_getLayouts',
  ),
  'layout_options_enable' => 
  array (
    'required' => false,
    'name' => 'layout_options_enable',
    'vname' => 'LBL_LAYOUT_OPTIONS_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'currency_enable' => 
  array (
    'required' => false,
    'name' => 'currency_enable',
    'vname' => 'LBL_CURRENCY_ENABLE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'currency_significant_digits' => 
  array (
    'required' => false,
    'name' => 'currency_significant_digits',
    'vname' => 'LBL_CURRENCY_SIGNIFICANT_DIGITS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '2',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'dependency' => 'equal($currency_significant_digit_ena,true)',
    'len' => 100,
    'size' => '20',
    'options' => 'currency_significant_digits_list',
    'studio' => 'visible',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('up_UserPreferences','up_UserPreferences', array('basic','team_security','assignable'));